# Copyright (c) 2026 Bryce M. Westheimer
# SPDX-License-Identifier: BSD-3-Clause

"""Type stubs for DTL Python bindings."""

from __future__ import annotations

from typing import Any, Optional, Sequence, Union

import numpy as np
import numpy.typing as npt

__version__: str
version_info: tuple[int, int, int]

# =============================================================================
# Feature detection
# =============================================================================

def has_mpi() -> bool: ...
def has_cuda() -> bool: ...
def has_hip() -> bool: ...
def has_nccl() -> bool: ...
def has_shmem() -> bool: ...

# =============================================================================
# Exceptions
# =============================================================================

class DTLError(Exception): ...
class CommunicationError(DTLError): ...
class MemoryError(DTLError, MemoryError): ...
class BoundsError(DTLError, IndexError): ...
class InvalidArgumentError(DTLError, ValueError): ...
class BackendError(DTLError): ...

# =============================================================================
# Policy enums and constants
# =============================================================================

class PartitionPolicy:
    BLOCK: int
    CYCLIC: int
    BLOCK_CYCLIC: int
    HASH: int
    REPLICATED: int

class PlacementPolicy:
    HOST: int
    DEVICE: int
    UNIFIED: int
    DEVICE_PREFERRED: int

class ExecutionPolicy:
    SEQ: int
    PAR: int
    ASYNC: int

PARTITION_BLOCK: int
PARTITION_CYCLIC: int
PARTITION_BLOCK_CYCLIC: int
PARTITION_HASH: int
PARTITION_REPLICATED: int

PLACEMENT_HOST: int
PLACEMENT_DEVICE: int
PLACEMENT_UNIFIED: int
PLACEMENT_DEVICE_PREFERRED: int

EXEC_SEQ: int
EXEC_PAR: int
EXEC_ASYNC: int

SUM: int
PROD: int
MIN: int
MAX: int

def placement_available(policy: int) -> bool: ...

# =============================================================================
# Context
# =============================================================================

class Context:
    def __init__(self, comm: Any = ..., device_id: int = ..., _native: Any = ...) -> None: ...
    @property
    def rank(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def is_root(self) -> bool: ...
    @property
    def device_id(self) -> int: ...
    @property
    def has_device(self) -> bool: ...
    @property
    def has_mpi(self) -> bool: ...
    @property
    def has_cuda(self) -> bool: ...
    @property
    def has_nccl(self) -> bool: ...
    @property
    def has_shmem(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    def barrier(self) -> None: ...
    def fence(self) -> None: ...
    def dup(self) -> Context: ...
    def split(self, color: int, key: int = ...) -> Context: ...
    def with_cuda(self, device_id: int) -> Context: ...
    def with_nccl(self, device_id: int) -> Context: ...
    def __enter__(self) -> Context: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __repr__(self) -> str: ...

# =============================================================================
# Environment
# =============================================================================

class Environment:
    def __init__(self) -> None: ...
    @staticmethod
    def is_initialized() -> bool: ...
    @staticmethod
    def ref_count() -> int: ...
    @property
    def has_mpi(self) -> bool: ...
    @property
    def has_cuda(self) -> bool: ...
    @property
    def has_hip(self) -> bool: ...
    @property
    def has_nccl(self) -> bool: ...
    @property
    def has_shmem(self) -> bool: ...
    @staticmethod
    def mpi_thread_level() -> int: ...
    def make_world_context(self, device_id: Optional[int] = ...) -> Context: ...
    def make_cpu_context(self) -> Context: ...
    def __enter__(self) -> Environment: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __repr__(self) -> str: ...

# =============================================================================
# Container factories
# =============================================================================

def DistributedVector(
    ctx: Context,
    size: int,
    dtype: Any = ...,
    fill: Any = ...,
    *,
    partition: Optional[int] = ...,
    placement: Optional[int] = ...,
    execution: Optional[int] = ...,
    device_id: int = ...,
    block_size: int = ...,
) -> Any: ...

def DistributedArray(
    ctx: Context,
    size: int,
    dtype: Any = ...,
    fill: Any = ...,
    *,
    partition: Optional[int] = ...,
    placement: Optional[int] = ...,
    execution: Optional[int] = ...,
    device_id: int = ...,
    block_size: int = ...,
) -> Any: ...

def DistributedTensor(
    ctx: Context,
    shape: Sequence[int],
    dtype: Any = ...,
    fill: Any = ...,
    *,
    partition: Optional[int] = ...,
    placement: Optional[int] = ...,
    execution: Optional[int] = ...,
    device_id: int = ...,
    block_size: int = ...,
) -> Any: ...

def DistributedSpan(vec_or_arr: Any) -> Any: ...

def DistributedMap(
    ctx: Context,
    key_dtype: Any = ...,
    value_dtype: Any = ...,
) -> Any: ...

# =============================================================================
# Collective operations
# =============================================================================

def allreduce(ctx: Context, value: Any, op: int = ...) -> Any: ...
def reduce(ctx: Context, value: Any, op: int = ..., root: int = ...) -> Any: ...
def broadcast(ctx: Context, value: Any, root: int = ...) -> Any: ...
def gather(ctx: Context, value: Any, root: int = ...) -> Any: ...
def scatter(ctx: Context, values: Any, root: int = ...) -> Any: ...
def allgather(ctx: Context, value: Any) -> Any: ...
def allgatherv(ctx: Context, value: Any) -> Any: ...
def alltoallv(ctx: Context, send_data: Any, send_counts: Any, recv_counts: Any) -> Any: ...
def gatherv(ctx: Context, data: Any, recvcounts: Any = ..., root: int = ...) -> Any: ...
def scatterv(ctx: Context, data: Any, sendcounts: Any, root: int = ...) -> Any: ...

# =============================================================================
# Point-to-point operations
# =============================================================================

def send(ctx: Context, data: Any, dest: int, tag: int = ...) -> None: ...
def recv(ctx: Context, source: int, tag: int = ..., dtype: Any = ..., count: int = ...) -> Any: ...
def sendrecv(ctx: Context, send_data: Any, dest: int, source: int, send_tag: int = ..., recv_tag: int = ...) -> Any: ...
def probe(ctx: Context, source: int = ..., tag: int = ...) -> dict[str, int]: ...
def iprobe(ctx: Context, source: int = ..., tag: int = ...) -> tuple[bool, Optional[dict[str, int]]]: ...

# =============================================================================
# Algorithms
# =============================================================================

def for_each_vector(vec: Any, func: Any) -> None: ...
def for_each_array(arr: Any, func: Any) -> None: ...
def copy_vector(src: Any, dst: Any) -> None: ...
def copy_array(src: Any, dst: Any) -> None: ...
def fill_vector(vec: Any, value: Any) -> None: ...
def fill_array(arr: Any, value: Any) -> None: ...
def find_vector(vec: Any, value: Any) -> int: ...
def find_if_vector(vec: Any, pred: Any) -> int: ...
def find_array(arr: Any, value: Any) -> int: ...
def find_if_array(arr: Any, pred: Any) -> int: ...
def count_vector(vec: Any, value: Any) -> int: ...
def count_if_vector(vec: Any, pred: Any) -> int: ...
def count_array(arr: Any, value: Any) -> int: ...
def count_if_array(arr: Any, pred: Any) -> int: ...
def reduce_local_vector(vec: Any, op: int = ...) -> Any: ...
def reduce_local_array(arr: Any, op: int = ...) -> Any: ...
def sort_vector(vec: Any, descending: bool = ...) -> None: ...
def sort_array(arr: Any, descending: bool = ...) -> None: ...
def minmax_vector(vec: Any) -> tuple[Any, Any]: ...
def minmax_array(arr: Any) -> tuple[Any, Any]: ...
def transform_vector(src: Any, dst: Any, func: Any) -> None: ...
def transform_array(src: Any, dst: Any, func: Any) -> None: ...
def inclusive_scan_vector(vec: Any, op: int = ...) -> Any: ...
def exclusive_scan_vector(vec: Any, init: Any = ..., op: int = ...) -> Any: ...
def inclusive_scan_array(arr: Any, op: int = ...) -> Any: ...
def exclusive_scan_array(arr: Any, init: Any = ..., op: int = ...) -> Any: ...
def all_of_vector(vec: Any, pred: Any) -> bool: ...
def any_of_vector(vec: Any, pred: Any) -> bool: ...
def none_of_vector(vec: Any, pred: Any) -> bool: ...
def all_of_array(arr: Any, pred: Any) -> bool: ...
def any_of_array(arr: Any, pred: Any) -> bool: ...
def none_of_array(arr: Any, pred: Any) -> bool: ...
def min_element_vector(vec: Any) -> Any: ...
def max_element_vector(vec: Any) -> Any: ...
def min_element_array(arr: Any) -> Any: ...
def max_element_array(arr: Any) -> Any: ...

# =============================================================================
# Async algorithms
# =============================================================================

class AlgorithmFuture:
    def get(self) -> Any: ...
    def wait(self) -> None: ...
    def test(self) -> bool: ...

def async_for_each(vec: Any, func: Any) -> AlgorithmFuture: ...
def async_transform(src: Any, dst: Any, func: Any) -> AlgorithmFuture: ...
def async_reduce(vec: Any, op: int = ...) -> AlgorithmFuture: ...
def async_sort(vec: Any, descending: bool = ...) -> AlgorithmFuture: ...

# =============================================================================
# Device migration
# =============================================================================

def to_device(vec: Any, device_id: int = ...) -> Any: ...
def to_host(vec: Any) -> Any: ...

# =============================================================================
# RMA operations
# =============================================================================

class Window:
    def __init__(self, ctx: Context, size: int) -> None: ...
    def fence(self) -> None: ...

def rma_put(win: Window, target: int, offset: int, data: Any) -> None: ...
def rma_get(win: Window, target: int, offset: int, size: int) -> Any: ...
def rma_accumulate(win: Window, target: int, offset: int, data: Any, op: int = ...) -> None: ...
def rma_fetch_and_add(win: Window, target: int, offset: int, value: Any) -> Any: ...
def rma_compare_and_swap(win: Window, target: int, offset: int, compare: Any, swap: Any) -> Any: ...

# =============================================================================
# MPMD
# =============================================================================

class RoleManager:
    def __init__(self, ctx: Context) -> None: ...

def intergroup_send(ctx: Context, data: Any, dest_role: int) -> None: ...
def intergroup_recv(ctx: Context, source_role: int) -> Any: ...

# =============================================================================
# Topology
# =============================================================================

class Topology:
    def __init__(self, ctx: Context) -> None: ...

# =============================================================================
# Futures
# =============================================================================

class Future:
    def get(self) -> Any: ...
    def wait(self) -> None: ...
    def test(self) -> bool: ...

def when_all(*futures: Future) -> Future: ...
def when_any(*futures: Future) -> tuple[int, Any]: ...

# =============================================================================
# Remote/RPC
# =============================================================================

class Action:
    def __init__(self, func: Any) -> None: ...

class Request:
    def get(self) -> Any: ...
    def wait(self) -> None: ...
    def test(self) -> bool: ...

def remote_invoke(ctx: Context, target_rank: int, action: Action, *args: Any) -> Any: ...
def remote_invoke_async(ctx: Context, target_rank: int, action: Action, *args: Any) -> Request: ...
