# Copyright (c) 2026 Bryce M. Westheimer
# SPDX-License-Identifier: BSD-3-Clause

"""
Type stubs for DTL native extension module.

This file provides type hints for the compiled _dtl module,
enabling static type checking with mypy and IDE autocompletion.
"""

from typing import Optional, Tuple, overload
import numpy as np
from numpy.typing import NDArray

# Version information
__version__: str
version_major: int
version_minor: int
version_patch: int

# Feature detection functions
def has_mpi() -> bool:
    """Check if MPI backend is available."""
    ...

def has_cuda() -> bool:
    """Check if CUDA backend is available."""
    ...

def has_hip() -> bool:
    """Check if HIP backend is available."""
    ...

def has_nccl() -> bool:
    """Check if NCCL is available."""
    ...

def has_shmem() -> bool:
    """Check if OpenSHMEM backend is available."""
    ...


# Context class
class Context:
    """Execution context for DTL operations."""

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, comm: Optional[object], device_id: int = -1) -> None: ...
    def __init__(
        self, comm: Optional[object] = None, device_id: int = -1
    ) -> None:
        """
        Create a DTL context.

        Args:
            comm: mpi4py MPI.Comm object (optional, None for MPI_COMM_WORLD)
            device_id: GPU device ID (default: -1 for CPU-only)
        """
        ...

    @property
    def rank(self) -> int:
        """Current rank (0 to size-1)."""
        ...

    @property
    def size(self) -> int:
        """Total number of ranks."""
        ...

    @property
    def is_root(self) -> bool:
        """True if this is rank 0."""
        ...

    @property
    def device_id(self) -> int:
        """GPU device ID (-1 for CPU-only)."""
        ...

    @property
    def has_device(self) -> bool:
        """True if GPU is enabled."""
        ...

    def barrier(self) -> None:
        """Synchronize all ranks."""
        ...

# Distributed Vector classes (one per dtype)
class DistributedVector_f64:
    """Distributed vector of float64 elements."""

    @overload
    def __init__(self, ctx: Context, size: int) -> None: ...
    @overload
    def __init__(self, ctx: Context, size: int, fill: float) -> None: ...
    def __init__(
        self, ctx: Context, size: int, fill: Optional[float] = None
    ) -> None: ...

    @property
    def global_size(self) -> int:
        """Total number of elements across all ranks."""
        ...

    @property
    def local_size(self) -> int:
        """Number of elements on this rank."""
        ...

    @property
    def local_offset(self) -> int:
        """Global index of first local element."""
        ...

    def local_view(self) -> NDArray[np.float64]:
        """Get a NumPy array view of local data."""
        ...

    def fill(self, value: float) -> None:
        """Fill all local elements with the given value."""
        ...

    def __len__(self) -> int: ...

class DistributedVector_f32:
    """Distributed vector of float32 elements."""

    @overload
    def __init__(self, ctx: Context, size: int) -> None: ...
    @overload
    def __init__(self, ctx: Context, size: int, fill: float) -> None: ...
    def __init__(
        self, ctx: Context, size: int, fill: Optional[float] = None
    ) -> None: ...

    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def local_offset(self) -> int: ...
    def local_view(self) -> NDArray[np.float32]: ...
    def fill(self, value: float) -> None: ...
    def __len__(self) -> int: ...

class DistributedVector_i64:
    """Distributed vector of int64 elements."""

    @overload
    def __init__(self, ctx: Context, size: int) -> None: ...
    @overload
    def __init__(self, ctx: Context, size: int, fill: int) -> None: ...
    def __init__(
        self, ctx: Context, size: int, fill: Optional[int] = None
    ) -> None: ...

    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def local_offset(self) -> int: ...
    def local_view(self) -> NDArray[np.int64]: ...
    def fill(self, value: int) -> None: ...
    def __len__(self) -> int: ...

class DistributedVector_i32:
    """Distributed vector of int32 elements."""

    @overload
    def __init__(self, ctx: Context, size: int) -> None: ...
    @overload
    def __init__(self, ctx: Context, size: int, fill: int) -> None: ...
    def __init__(
        self, ctx: Context, size: int, fill: Optional[int] = None
    ) -> None: ...

    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def local_offset(self) -> int: ...
    def local_view(self) -> NDArray[np.int32]: ...
    def fill(self, value: int) -> None: ...
    def __len__(self) -> int: ...

class DistributedVector_u64:
    """Distributed vector of uint64 elements."""

    @overload
    def __init__(self, ctx: Context, size: int) -> None: ...
    @overload
    def __init__(self, ctx: Context, size: int, fill: int) -> None: ...
    def __init__(
        self, ctx: Context, size: int, fill: Optional[int] = None
    ) -> None: ...

    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def local_offset(self) -> int: ...
    def local_view(self) -> NDArray[np.uint64]: ...
    def fill(self, value: int) -> None: ...
    def __len__(self) -> int: ...

class DistributedVector_u32:
    """Distributed vector of uint32 elements."""

    @overload
    def __init__(self, ctx: Context, size: int) -> None: ...
    @overload
    def __init__(self, ctx: Context, size: int, fill: int) -> None: ...
    def __init__(
        self, ctx: Context, size: int, fill: Optional[int] = None
    ) -> None: ...

    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def local_offset(self) -> int: ...
    def local_view(self) -> NDArray[np.uint32]: ...
    def fill(self, value: int) -> None: ...
    def __len__(self) -> int: ...

class DistributedVector_u8:
    """Distributed vector of uint8 elements."""

    @overload
    def __init__(self, ctx: Context, size: int) -> None: ...
    @overload
    def __init__(self, ctx: Context, size: int, fill: int) -> None: ...
    def __init__(
        self, ctx: Context, size: int, fill: Optional[int] = None
    ) -> None: ...

    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def local_offset(self) -> int: ...
    def local_view(self) -> NDArray[np.uint8]: ...
    def fill(self, value: int) -> None: ...
    def __len__(self) -> int: ...

class DistributedVector_i8:
    """Distributed vector of int8 elements."""

    @overload
    def __init__(self, ctx: Context, size: int) -> None: ...
    @overload
    def __init__(self, ctx: Context, size: int, fill: int) -> None: ...
    def __init__(
        self, ctx: Context, size: int, fill: Optional[int] = None
    ) -> None: ...

    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def local_offset(self) -> int: ...
    def local_view(self) -> NDArray[np.int8]: ...
    def fill(self, value: int) -> None: ...
    def __len__(self) -> int: ...

# Distributed Tensor classes (one per dtype)
class DistributedTensor_f64:
    """Distributed tensor of float64 elements."""

    @overload
    def __init__(self, ctx: Context, shape: Tuple[int, ...]) -> None: ...
    @overload
    def __init__(
        self, ctx: Context, shape: Tuple[int, ...], fill: float
    ) -> None: ...
    def __init__(
        self, ctx: Context, shape: Tuple[int, ...], fill: Optional[float] = None
    ) -> None: ...

    @property
    def ndim(self) -> int:
        """Number of dimensions."""
        ...

    @property
    def shape(self) -> Tuple[int, ...]:
        """Global shape tuple."""
        ...

    @property
    def local_shape(self) -> Tuple[int, ...]:
        """Local shape tuple on this rank."""
        ...

    @property
    def global_size(self) -> int:
        """Total number of elements across all ranks."""
        ...

    @property
    def local_size(self) -> int:
        """Number of elements on this rank."""
        ...

    def local_view(self) -> NDArray[np.float64]:
        """Get a NumPy array view of local data."""
        ...

    def fill(self, value: float) -> None:
        """Fill all local elements with the given value."""
        ...

class DistributedTensor_f32:
    """Distributed tensor of float32 elements."""

    @overload
    def __init__(self, ctx: Context, shape: Tuple[int, ...]) -> None: ...
    @overload
    def __init__(
        self, ctx: Context, shape: Tuple[int, ...], fill: float
    ) -> None: ...
    def __init__(
        self, ctx: Context, shape: Tuple[int, ...], fill: Optional[float] = None
    ) -> None: ...

    @property
    def ndim(self) -> int: ...
    @property
    def shape(self) -> Tuple[int, ...]: ...
    @property
    def local_shape(self) -> Tuple[int, ...]: ...
    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    def local_view(self) -> NDArray[np.float32]: ...
    def fill(self, value: float) -> None: ...

class DistributedTensor_i64:
    """Distributed tensor of int64 elements."""

    @overload
    def __init__(self, ctx: Context, shape: Tuple[int, ...]) -> None: ...
    @overload
    def __init__(
        self, ctx: Context, shape: Tuple[int, ...], fill: int
    ) -> None: ...
    def __init__(
        self, ctx: Context, shape: Tuple[int, ...], fill: Optional[int] = None
    ) -> None: ...

    @property
    def ndim(self) -> int: ...
    @property
    def shape(self) -> Tuple[int, ...]: ...
    @property
    def local_shape(self) -> Tuple[int, ...]: ...
    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    def local_view(self) -> NDArray[np.int64]: ...
    def fill(self, value: int) -> None: ...

class DistributedTensor_i32:
    """Distributed tensor of int32 elements."""

    @overload
    def __init__(self, ctx: Context, shape: Tuple[int, ...]) -> None: ...
    @overload
    def __init__(
        self, ctx: Context, shape: Tuple[int, ...], fill: int
    ) -> None: ...
    def __init__(
        self, ctx: Context, shape: Tuple[int, ...], fill: Optional[int] = None
    ) -> None: ...

    @property
    def ndim(self) -> int: ...
    @property
    def shape(self) -> Tuple[int, ...]: ...
    @property
    def local_shape(self) -> Tuple[int, ...]: ...
    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    def local_view(self) -> NDArray[np.int32]: ...
    def fill(self, value: int) -> None: ...


# Distributed Span classes (one per dtype)
class DistributedSpan_f64:
    @overload
    def __init__(self, source: object) -> None: ...

    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def empty(self) -> int: ...
    @property
    def is_valid(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def num_ranks(self) -> int: ...
    def local_view(self) -> NDArray[np.float64]: ...
    def to_numpy(self) -> NDArray[np.float64]: ...
    def from_numpy(self, arr: NDArray[np.float64]) -> None: ...
    def get_local(self, idx: int) -> float: ...
    def set_local(self, idx: int, value: float) -> None: ...
    def first(self, count: int) -> "DistributedSpan_f64": ...
    def last(self, count: int) -> "DistributedSpan_f64": ...
    def subspan(self, offset: int, count: int = ...) -> "DistributedSpan_f64": ...
    def __len__(self) -> int: ...


class DistributedSpan_f32:
    @overload
    def __init__(self, source: object) -> None: ...
    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def empty(self) -> int: ...
    @property
    def is_valid(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def num_ranks(self) -> int: ...
    def local_view(self) -> NDArray[np.float32]: ...
    def to_numpy(self) -> NDArray[np.float32]: ...
    def from_numpy(self, arr: NDArray[np.float32]) -> None: ...
    def get_local(self, idx: int) -> float: ...
    def set_local(self, idx: int, value: float) -> None: ...
    def first(self, count: int) -> "DistributedSpan_f32": ...
    def last(self, count: int) -> "DistributedSpan_f32": ...
    def subspan(self, offset: int, count: int = ...) -> "DistributedSpan_f32": ...
    def __len__(self) -> int: ...


class DistributedSpan_i64:
    @overload
    def __init__(self, source: object) -> None: ...
    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def empty(self) -> int: ...
    @property
    def is_valid(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def num_ranks(self) -> int: ...
    def local_view(self) -> NDArray[np.int64]: ...
    def to_numpy(self) -> NDArray[np.int64]: ...
    def from_numpy(self, arr: NDArray[np.int64]) -> None: ...
    def get_local(self, idx: int) -> int: ...
    def set_local(self, idx: int, value: int) -> None: ...
    def first(self, count: int) -> "DistributedSpan_i64": ...
    def last(self, count: int) -> "DistributedSpan_i64": ...
    def subspan(self, offset: int, count: int = ...) -> "DistributedSpan_i64": ...
    def __len__(self) -> int: ...


class DistributedSpan_i32:
    @overload
    def __init__(self, source: object) -> None: ...
    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def empty(self) -> int: ...
    @property
    def is_valid(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def num_ranks(self) -> int: ...
    def local_view(self) -> NDArray[np.int32]: ...
    def to_numpy(self) -> NDArray[np.int32]: ...
    def from_numpy(self, arr: NDArray[np.int32]) -> None: ...
    def get_local(self, idx: int) -> int: ...
    def set_local(self, idx: int, value: int) -> None: ...
    def first(self, count: int) -> "DistributedSpan_i32": ...
    def last(self, count: int) -> "DistributedSpan_i32": ...
    def subspan(self, offset: int, count: int = ...) -> "DistributedSpan_i32": ...
    def __len__(self) -> int: ...


class DistributedSpan_u64:
    @overload
    def __init__(self, source: object) -> None: ...
    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def empty(self) -> int: ...
    @property
    def is_valid(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def num_ranks(self) -> int: ...
    def local_view(self) -> NDArray[np.uint64]: ...
    def to_numpy(self) -> NDArray[np.uint64]: ...
    def from_numpy(self, arr: NDArray[np.uint64]) -> None: ...
    def get_local(self, idx: int) -> int: ...
    def set_local(self, idx: int, value: int) -> None: ...
    def first(self, count: int) -> "DistributedSpan_u64": ...
    def last(self, count: int) -> "DistributedSpan_u64": ...
    def subspan(self, offset: int, count: int = ...) -> "DistributedSpan_u64": ...
    def __len__(self) -> int: ...


class DistributedSpan_u32:
    @overload
    def __init__(self, source: object) -> None: ...
    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def empty(self) -> int: ...
    @property
    def is_valid(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def num_ranks(self) -> int: ...
    def local_view(self) -> NDArray[np.uint32]: ...
    def to_numpy(self) -> NDArray[np.uint32]: ...
    def from_numpy(self, arr: NDArray[np.uint32]) -> None: ...
    def get_local(self, idx: int) -> int: ...
    def set_local(self, idx: int, value: int) -> None: ...
    def first(self, count: int) -> "DistributedSpan_u32": ...
    def last(self, count: int) -> "DistributedSpan_u32": ...
    def subspan(self, offset: int, count: int = ...) -> "DistributedSpan_u32": ...
    def __len__(self) -> int: ...


class DistributedSpan_u8:
    @overload
    def __init__(self, source: object) -> None: ...
    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def empty(self) -> int: ...
    @property
    def is_valid(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def num_ranks(self) -> int: ...
    def local_view(self) -> NDArray[np.uint8]: ...
    def to_numpy(self) -> NDArray[np.uint8]: ...
    def from_numpy(self, arr: NDArray[np.uint8]) -> None: ...
    def get_local(self, idx: int) -> int: ...
    def set_local(self, idx: int, value: int) -> None: ...
    def first(self, count: int) -> "DistributedSpan_u8": ...
    def last(self, count: int) -> "DistributedSpan_u8": ...
    def subspan(self, offset: int, count: int = ...) -> "DistributedSpan_u8": ...
    def __len__(self) -> int: ...


class DistributedSpan_i8:
    @overload
    def __init__(self, source: object) -> None: ...
    @property
    def global_size(self) -> int: ...
    @property
    def local_size(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def empty(self) -> int: ...
    @property
    def is_valid(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def num_ranks(self) -> int: ...
    def local_view(self) -> NDArray[np.int8]: ...
    def to_numpy(self) -> NDArray[np.int8]: ...
    def from_numpy(self, arr: NDArray[np.int8]) -> None: ...
    def get_local(self, idx: int) -> int: ...
    def set_local(self, idx: int, value: int) -> None: ...
    def first(self, count: int) -> "DistributedSpan_i8": ...
    def last(self, count: int) -> "DistributedSpan_i8": ...
    def subspan(self, offset: int, count: int = ...) -> "DistributedSpan_i8": ...
    def __len__(self) -> int: ...
